# Используем актуальный образ
FROM python:3.10-slim-bullseye

# 1. Системные зависимости (теперь ссылки будут работать)
RUN apt-get update && apt-get install -y \
    libpq-dev \
    gcc \
    --no-install-recommends \
    && rm -rf /var/lib/apt/lists/*

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /usr/src/app

COPY requirements.txt .
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt && \
    pip install gunicorn

COPY . .

CMD ["gunicorn", "--bind", "0.0.0.0:8000", "dj_ac.wsgi:application"]