FROM python:3.10-slim-buster

# 1. Системные зависимости для Postgres и сборки пакетов
RUN apt-get update && apt-get install -y \
    libpq-dev \
    gcc \
    && rm -rf /var/lib/apt/lists/*

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /usr/src/app

# 2. Оптимизируем кэш: сначала ставим зависимости
COPY requirements.txt .
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -r requirements.txt && \
    pip install gunicorn  # Убедись, что gunicorn есть в системе

# 3. Копируем проект
COPY . .

# 4. Команда запуска (Боевой режим!)
# Мы запускаем через Gunicorn на порту 8000. 
# Замени 'dj_ac' на имя папки, где лежит твой файл wsgi.py
CMD ["gunicorn", "--bind", "0.0.0.0:8000", "dj_ac.wsgi:application"]