# Generated by Django 4.2.4 on 2026-01-19 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TGUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
                ('tg_id', models.BigIntegerField(db_index=True, unique=True, verbose_name='id Telegram')),
                ('fullname', models.CharField(max_length=255)),
                ('age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('email', models.EmailField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('region', models.CharField(blank=True, choices=[('navoi', 'Navoi'), ('qashqadaryo', 'Qashqadaryo'), ('tashkent', 'Tashkent'), ('samarkand', 'Samarkand'), ('andijon', 'Andijon'), ('fargona', 'Farg‘ona'), ('namangan', 'Namangan'), ('bukhara', 'Buxoro'), ('khorezm', 'Xorazm'), ('sirdaryo', 'Sirdaryo'), ('jizzakh', 'Jizzax'), ('surkhandaryo', 'Surxondaryo'), ('karakalpakstan', 'Qoraqalpog‘iston')], max_length=20, null=True, verbose_name='Hudud')),
                ('education_place', models.CharField(blank=True, max_length=255, null=True, verbose_name='O‘qish joyi')),
            ],
            options={
                'verbose_name': 'пользователь',
                'verbose_name_plural': 'пользователи',
            },
        ),
        migrations.CreateModel(
            name='TeamMemberYashilQullar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
                ('full_name', models.CharField(max_length=255, verbose_name='To‘liq ism')),
                ('education', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ta’lim / O‘qish joyi')),
                ('skills', models.TextField(blank=True, null=True, verbose_name='Ko‘nikmalar')),
                ('telegram_username', models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram username')),
                ('motto', models.CharField(blank=True, max_length=255, null=True, verbose_name='Shior')),
                ('tg_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team_member', to='app_telegram.tguser', verbose_name='Telegram foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Team member (Yashil Qullar)',
                'verbose_name_plural': 'Team members (Yashil Qullar)',
            },
        ),
    ]
