# Generated by Django 4.2.4 on 2026-02-03 14:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app_telegram', '0002_teammemberyashilqullar_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='EcoProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
                ('title', models.CharField(max_length=255, verbose_name='Nomi')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('date', models.DateTimeField(verbose_name='Sana va vaqt')),
                ('location', models.CharField(max_length=255, verbose_name='Joy')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faolmi')),
                ('max_participants', models.PositiveIntegerField(blank=True, null=True, verbose_name='Maksimal ishtirokchilar soni')),
            ],
            options={
                'verbose_name': 'Eco loyiha',
                'verbose_name_plural': 'Eco loyihalar',
            },
        ),
        migrations.CreateModel(
            name='ProjectParticipation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='дата обновления')),
                ('qr_token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='QR token')),
                ('status', models.CharField(choices=[('registered', 'Ro‘yxatdan o‘tdi'), ('attended', 'Keldi'), ('canceled', 'Bekor qilindi')], default='registered', max_length=20, verbose_name='Holat')),
                ('checked_in_at', models.DateTimeField(blank=True, null=True, verbose_name='Keldi vaqti')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='app_telegram.ecoproject', verbose_name='Loyiha')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='app_telegram.tguser', verbose_name='Telegram foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Loyiha ishtirokchisi',
                'verbose_name_plural': 'Loyiha ishtirokchilari',
                'unique_together': {('user', 'project')},
            },
        ),
    ]
