# Generated by Django 4.2.4 on 2026-02-03 15:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app_telegram', '0003_ecoproject_projectparticipation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectparticipation',
            name='qr_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
