# Generated by Django 4.2.4 on 2026-02-17 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_telegram', '0005_tguser_experience_alter_tguser_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='tguser',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='users_photos/', verbose_name='Profil rasmi'),
        ),
    ]
