# Generated by Django 4.2.4 on 2026-02-17 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_telegram', '0007_rename_motto_teammemberyashilqullar_focus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammemberyashilqullar',
            name='focus',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='focus'),
        ),
    ]
