# Generated by Django 4.2.4 on 2026-02-17 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_telegram', '0008_alter_teammemberyashilqullar_focus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammemberyashilqullar',
            name='focus',
            field=models.CharField(choices=[('founder', 'Founder'), ('digital', 'Digital Lead'), ('media', 'Media Lead'), ('organization', 'Organization')], max_length=255),
        ),
    ]
