# Generated by Django 4.2.4 on 2026-02-17 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_telegram', '0009_alter_teammemberyashilqullar_focus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammemberyashilqullar',
            name='education',
        ),
        migrations.RemoveField(
            model_name='teammemberyashilqullar',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='teammemberyashilqullar',
            name='image',
        ),
    ]
