# Generated by Django 4.2.4 on 2026-02-17 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_telegram', '0010_remove_teammemberyashilqullar_education_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tguser',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Username'),
        ),
    ]
