# Generated by Django 4.2.4 on 2026-03-25 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_telegram', '0011_tguser_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Hamkor nomi')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='partners/', verbose_name='Logotip')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif (ixtiyoriy)')),
                ('website', models.URLField(blank=True, null=True, verbose_name='Veb-sayt')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='Instagram')),
                ('telegram', models.URLField(blank=True, null=True, verbose_name='Telegram')),
            ],
            options={
                'verbose_name': 'Hamkorlar',
            },
        ),
    ]
