# Generated by Django 4.2.4 on 2026-03-31 19:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_telegram', '0012_partner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partner',
            options={'verbose_name': 'Партнер', 'verbose_name_plural': 'Партнеры'},
        ),
        migrations.RemoveField(
            model_name='partner',
            name='website',
        ),
        migrations.AddField(
            model_name='partner',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partner',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Показывать в боте'),
        ),
        migrations.AddField(
            model_name='partner',
            name='linkedin',
            field=models.URLField(blank=True, null=True, verbose_name='LinkedIn Link'),
        ),
        migrations.AddField(
            model_name='partner',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='дата обновления'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание партнерства'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='instagram',
            field=models.URLField(blank=True, null=True, verbose_name='Instagram Link'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='partners_logos/', verbose_name='Логотип'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Имя компании'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='telegram',
            field=models.URLField(blank=True, null=True, verbose_name='Telegram Link'),
        ),
    ]
