# Generated by Django 4.2.4 on 2026-03-31 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_telegram', '0013_alter_partner_options_remove_partner_website_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tguser',
            name='balance',
            field=models.PositiveIntegerField(default=0, verbose_name='Эко-баллы'),
        ),
    ]
