# Generated by Django 4.2.4 on 2026-03-31 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_telegram', '0014_tguser_balance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectparticipation',
            options={'ordering': ('-created',)},
        ),
        migrations.AlterUniqueTogether(
            name='projectparticipation',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='ecoproject',
            name='location',
        ),
        migrations.AddField(
            model_name='ecoproject',
            name='channel_link',
            field=models.URLField(blank=True, null=True, verbose_name='Telegram kanal linki'),
        ),
        migrations.AddField(
            model_name='ecoproject',
            name='location_name',
            field=models.CharField(default=1, max_length=255, verbose_name='Joy nomi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ecoproject',
            name='location_url',
            field=models.URLField(blank=True, null=True, verbose_name='Google/Yandex Map linki'),
        ),
        migrations.AddField(
            model_name='ecoproject',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='projects/', verbose_name='Rasm'),
        ),
        migrations.AddField(
            model_name='ecoproject',
            name='secret_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Maxfiy kod'),
        ),
        migrations.AlterField(
            model_name='ecoproject',
            name='max_participants',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Maksimal ishtirokchilar'),
        ),
        migrations.AlterField(
            model_name='projectparticipation',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_telegram.ecoproject'),
        ),
        migrations.AlterField(
            model_name='projectparticipation',
            name='status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('registered', 'Qabul qilindi'), ('attended', 'Keldi'), ('rejected', 'Rad etildi')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='projectparticipation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_telegram.tguser'),
        ),
        migrations.RemoveField(
            model_name='projectparticipation',
            name='checked_in_at',
        ),
        migrations.RemoveField(
            model_name='projectparticipation',
            name='qr_token',
        ),
    ]
