# Generated by Django 4.2.4 on 2026-03-31 20:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_telegram', '0015_alter_projectparticipation_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectparticipation',
            options={'verbose_name': 'Loyihada ishtirok', 'verbose_name_plural': 'Loyihalarda ishtirok'},
        ),
        migrations.RemoveField(
            model_name='ecoproject',
            name='channel_link',
        ),
        migrations.RemoveField(
            model_name='ecoproject',
            name='created',
        ),
        migrations.RemoveField(
            model_name='ecoproject',
            name='location_url',
        ),
        migrations.RemoveField(
            model_name='ecoproject',
            name='max_participants',
        ),
        migrations.RemoveField(
            model_name='ecoproject',
            name='updated',
        ),
        migrations.AddField(
            model_name='projectparticipation',
            name='applied_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ecoproject',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faolmi?'),
        ),
        migrations.AlterField(
            model_name='ecoproject',
            name='location_name',
            field=models.CharField(max_length=255, verbose_name='Manzil nomi'),
        ),
        migrations.AlterField(
            model_name='ecoproject',
            name='secret_code',
            field=models.CharField(default=1, max_length=50, unique=True, verbose_name='Maxfiy kod'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ecoproject',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Loyiha nomi'),
        ),
        migrations.AlterField(
            model_name='projectparticipation',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='app_telegram.ecoproject'),
        ),
        migrations.AlterField(
            model_name='projectparticipation',
            name='status',
            field=models.CharField(choices=[('pending', 'Kutilmoqda'), ('registered', 'Qabul qilindi'), ('attended', 'Ishtirok etdi'), ('rejected', 'Rad etildi')], default='pending', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='projectparticipation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='app_telegram.tguser'),
        ),
        migrations.AlterUniqueTogether(
            name='projectparticipation',
            unique_together={('user', 'project')},
        ),
        migrations.RemoveField(
            model_name='projectparticipation',
            name='created',
        ),
        migrations.RemoveField(
            model_name='projectparticipation',
            name='updated',
        ),
    ]
