# Generated by Django 4.2.4 on 2026-03-31 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_telegram', '0016_alter_projectparticipation_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectparticipation',
            options={'verbose_name': 'Loyihada ishtiroк', 'verbose_name_plural': 'Loyihalarda ishtiroк'},
        ),
    ]
