# Generated by Django 4.2.4 on 2026-03-31 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_telegram', '0017_alter_projectparticipation_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectparticipation',
            options={'verbose_name': 'Ishtirokchi', 'verbose_name_plural': 'Ishtirokchilar'},
        ),
        migrations.AlterField(
            model_name='projectparticipation',
            name='status',
            field=models.CharField(choices=[('attended', '✅ Keldi (Пришёл)'), ('rejected', '❌ Kelmadi / Rad etildi (Отмена)')], max_length=20, verbose_name='Status'),
        ),
    ]
