# Generated by Django 4.2.4 on 2026-04-03 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_telegram', '0018_alter_projectparticipation_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ecoproject',
            name='secret_code',
        ),
        migrations.AddField(
            model_name='ecoproject',
            name='chat_link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на чат (для принятых)'),
        ),
        migrations.AlterField(
            model_name='projectparticipation',
            name='status',
            field=models.CharField(choices=[('pending', '⏳ Кутиш (Ожидание)'), ('approved', '✅ Қабул қилинди (Принят)'), ('attended', '🌟 Келди (Пришел +10 баллов)'), ('rejected', '❌ Рад этилди (Отклонен)')], default='pending', max_length=20, verbose_name='Status'),
        ),
    ]
