# Generated by Django 4.2.4 on 2026-04-03 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_telegram', '0019_remove_ecoproject_secret_code_ecoproject_chat_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammemberyashilqullar',
            name='tg_user',
        ),
        migrations.AddField(
            model_name='teammemberyashilqullar',
            name='fullname',
            field=models.CharField(default=1, max_length=255, verbose_name='F.I.SH (Имя)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teammemberyashilqullar',
            name='photo',
            field=models.ImageField(default=1, upload_to='team_photos/', verbose_name='Rasm (Фото)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='teammemberyashilqullar',
            name='focus',
            field=models.CharField(choices=[('founder', 'Founder'), ('digital', 'Digital Lead'), ('media', 'Media Lead'), ('organization', 'Organization')], max_length=255, verbose_name="Yo'nalishi (Роль)"),
        ),
        migrations.AlterField(
            model_name='teammemberyashilqullar',
            name='skills',
            field=models.TextField(blank=True, null=True, verbose_name='Ko‘nikmalar (Навыки)'),
        ),
        migrations.AlterField(
            model_name='teammemberyashilqullar',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram Username (@...)'),
        ),
    ]
