# Generated by Django 4.2.4 on 2026-04-03 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_telegram', '0020_remove_teammemberyashilqullar_tg_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecoproject',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
    ]
