# Generated by Django 4.2.4 on 2026-05-09 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_telegram', '0021_alter_ecoproject_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecoproject',
            name='region',
            field=models.CharField(choices=[('karakalpakstan', 'Qoraqalpogʻiston Respublikasi'), ('andijon', 'Andijon viloyati'), ('bukhara', 'Buxoro viloyati'), ('fargona', 'Fargʻona viloyati'), ('jizzakh', 'Jizzax viloyati'), ('khorezm', 'Xorazm viloyati'), ('namangan', 'Namangan viloyati'), ('navoi', 'Navoiy viloyati'), ('qashqadaryo', 'Qashqadaryo viloyati'), ('samarkand', 'Samarqand viloyati'), ('sirdaryo', 'Sirdaryo viloyati'), ('surkhandaryo', 'Surxondaryo viloyati'), ('tashkent_v', 'Toshkent viloyati'), ('tashkent_s', 'Toshkent shahri')], default='tashkent_s', max_length=20, verbose_name='Qaysi viloyat uchun?'),
        ),
    ]
