# Generated by Django 4.2.4 on 2026-05-09 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_telegram', '0022_ecoproject_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecoproject',
            name='max_participants',
            field=models.PositiveIntegerField(default=100, verbose_name='Макс. участников'),
        ),
    ]
