# Generated by Django 4.2.4 on 2026-05-09 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_telegram', '0023_ecoproject_max_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='tguser',
            name='is_tester',
            field=models.BooleanField(default=False, verbose_name='Тестировщик'),
        ),
    ]
