# Generated by Django 4.2.4 on 2026-05-10 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_telegram', '0024_tguser_is_tester'),
    ]

    operations = [
        migrations.AddField(
            model_name='tguser',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
