# Generated by Django 4.2.4 on 2026-06-11 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_telegram', '0025_tguser_is_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_telegram.ecoproject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_telegram.tguser')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'unique_together': {('project', 'user')},
            },
        ),
    ]
