# Generated by Django 4.2.4 on 2026-06-28 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_telegram', '0026_projectnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='tguser',
            name='role',
            field=models.CharField(choices=[('volunteer', 'Волонтер'), ('coordinator', 'Координатор'), ('mobilograph', 'Мобилограф'), ('it', 'IT Специалист'), ('organizer', 'Организатор'), ('Founder', 'Оснаватель')], default='volunteer', max_length=20, verbose_name='Статус / Роль'),
        ),
    ]
