# Generated by Django 4.2.4 on 2026-07-01 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_telegram', '0027_tguser_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('title_uz', models.CharField(max_length=255, null=True)),
                ('title_ru', models.CharField(max_length=255, null=True)),
                ('slug', models.SlugField(unique=True)),
                ('cover_image', models.ImageField(upload_to='blog/covers/')),
                ('content', models.TextField()),
                ('content_en', models.TextField(null=True)),
                ('content_uz', models.TextField(null=True)),
                ('content_ru', models.TextField(null=True)),
                ('author_name', models.CharField(max_length=100)),
                ('author_role', models.CharField(blank=True, max_length=100, null=True)),
                ('read_time_minutes', models.PositiveIntegerField(default=3)),
                ('likes_count', models.PositiveIntegerField(default=0)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('name_en', models.CharField(max_length=50, null=True)),
                ('name_uz', models.CharField(max_length=50, null=True)),
                ('name_ru', models.CharField(max_length=50, null=True)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='teammemberyashilqullar',
            name='instagram',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Instagram username (@...)'),
        ),
        migrations.AddField(
            model_name='teammemberyashilqullar',
            name='skills_en',
            field=models.TextField(blank=True, null=True, verbose_name='Ko‘nikmalar (Навыки)'),
        ),
        migrations.AddField(
            model_name='teammemberyashilqullar',
            name='skills_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Ko‘nikmalar (Навыки)'),
        ),
        migrations.AddField(
            model_name='teammemberyashilqullar',
            name='skills_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Ko‘nikmalar (Навыки)'),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='role',
            field=models.CharField(choices=[('volunteer', 'Volunteer'), ('coordinator', 'Coordinator'), ('mobilograph', 'Mobilographer'), ('it', 'IT Specialist'), ('organizer', 'Organizer'), ('Founder', 'Founder')], default='volunteer', max_length=20, verbose_name='Статус / Роль'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('likes_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='app_telegram.article')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='app_telegram.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_telegram.tguser')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(related_name='articles', to='app_telegram.tag'),
        ),
    ]
