# Generated by Django 4.2.4 on 2026-07-03 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_telegram', '0028_article_tag_teammemberyashilqullar_instagram_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('confirmed', 'confirmed')], default='pending', max_length=20)),
                ('tg_id', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Токен входа',
                'verbose_name_plural': 'Токены входа',
            },
        ),
    ]
