# Generated by Django 4.2.4 on 2026-07-03 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_telegram', '0029_logintoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(verbose_name='Baho (1-5)')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Fikr-mulohaza')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='app_telegram.ecoproject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='app_telegram.tguser')),
            ],
            options={
                'verbose_name': 'Fikr-mulohaza',
                'verbose_name_plural': 'Fikr-mulohazalar',
                'unique_together': {('user', 'project')},
            },
        ),
    ]
