# Generated by Django 4.2.4 on 2026-07-03 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_telegram', '0030_eventfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='blog/videos/', verbose_name='Video fayl (yuklash)'),
        ),
        migrations.AddField(
            model_name='article',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='Video havolasi (YouTube va h.k.)'),
        ),
        migrations.CreateModel(
            name='ArticleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='blog/gallery/')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib raqami')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='app_telegram.article')),
            ],
            options={
                'verbose_name': 'Rasm (galereya)',
                'verbose_name_plural': 'Rasmlar (galereya)',
                'ordering': ['order'],
            },
        ),
    ]
