# Generated by Django 4.2.4 on 2026-07-03 21:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_telegram', '0032_alter_article_cover_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='author_name',
        ),
        migrations.RemoveField(
            model_name='article',
            name='author_role',
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='app_telegram.teammemberyashilqullar', verbose_name='Muallif (jamoadan tanlang)'),
        ),
    ]
