# Generated by Django 4.2.4 on 2026-07-03 21:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_telegram', '0033_remove_article_author_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_admin': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='app_telegram.tguser', verbose_name='Muallif (faqat admin foydalanuvchilar)'),
        ),
    ]
