# Generated by Django 4.2.4 on 2026-07-07 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_telegram', '0035_alter_article_content_alter_article_content_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tguser',
            name='auth_provider',
            field=models.CharField(choices=[('telegram', 'Telegram Bot'), ('email', 'Email + Password'), ('google', 'Google')], default='telegram', max_length=20, verbose_name='Способ регистрации'),
        ),
        migrations.AddField(
            model_name='tguser',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Пароль (хэш)'),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='tg_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, unique=True, verbose_name='id Telegram'),
        ),
    ]
