# Generated by Django 4.2.4 on 2026-07-08 00:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_telegram', '0036_tguser_auth_provider_tguser_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecoproject',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='ecoproject',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='ecoproject',
            name='description_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AddField(
            model_name='ecoproject',
            name='location_name_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Manzil nomi'),
        ),
        migrations.AddField(
            model_name='ecoproject',
            name='location_name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Manzil nomi'),
        ),
        migrations.AddField(
            model_name='ecoproject',
            name='location_name_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Manzil nomi'),
        ),
        migrations.AddField(
            model_name='ecoproject',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Loyiha nomi'),
        ),
        migrations.AddField(
            model_name='ecoproject',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Loyiha nomi'),
        ),
        migrations.AddField(
            model_name='ecoproject',
            name='title_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Loyiha nomi'),
        ),
        migrations.CreateModel(
            name='EcoProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/gallery/')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib raqami')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='app_telegram.ecoproject')),
            ],
            options={
                'verbose_name': 'Loyiha rasmi (galereya)',
                'verbose_name_plural': 'Loyiha rasmlari (galereya)',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CommentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_likes', to='app_telegram.comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_telegram.tguser')),
            ],
            options={
                'verbose_name': 'Лайк комментария',
                'verbose_name_plural': 'Лайки комментариев',
                'unique_together': {('comment', 'user')},
            },
        ),
        migrations.CreateModel(
            name='ArticleLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_likes', to='app_telegram.article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_telegram.tguser')),
            ],
            options={
                'verbose_name': 'Лайк статьи',
                'verbose_name_plural': 'Лайки статей',
                'unique_together': {('article', 'user')},
            },
        ),
    ]
