# Generated by Django 4.2.4 on 2026-07-08 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_telegram', '0037_ecoproject_description_en_ecoproject_description_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecoproject',
            name='likes_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Лайки'),
        ),
        migrations.CreateModel(
            name='EcoProjectComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('likes_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='app_telegram.ecoprojectcomment')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='app_telegram.ecoproject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_telegram.tguser')),
            ],
        ),
        migrations.CreateModel(
            name='EcoProjectLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_likes', to='app_telegram.ecoproject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_telegram.tguser')),
            ],
            options={
                'unique_together': {('project', 'user')},
            },
        ),
        migrations.CreateModel(
            name='EcoProjectCommentLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_likes', to='app_telegram.ecoprojectcomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_telegram.tguser')),
            ],
            options={
                'unique_together': {('comment', 'user')},
            },
        ),
    ]
