# Generated by Django 4.2.4 on 2026-07-08 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_telegram', '0038_ecoproject_likes_count_ecoprojectcomment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ecoproject',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='ecoproject',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='ecoproject',
            name='description_uz',
        ),
        migrations.RemoveField(
            model_name='ecoproject',
            name='location_name_en',
        ),
        migrations.RemoveField(
            model_name='ecoproject',
            name='location_name_ru',
        ),
        migrations.RemoveField(
            model_name='ecoproject',
            name='location_name_uz',
        ),
        migrations.RemoveField(
            model_name='ecoproject',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='ecoproject',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='ecoproject',
            name='title_uz',
        ),
    ]
