# Generated by Django 4.2.4 on 2026-07-12 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_telegram', '0039_remove_ecoproject_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tguser',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='Bio'),
        ),
    ]
