# Generated by Django 4.2.4 on 2026-07-17 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_telegram', '0040_tguser_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tguser',
            name='role',
            field=models.CharField(choices=[('volunteer', 'Volunteer'), ('head_coordinator', 'Head of Coordinators'), ('main_coordinator', 'Main Coordinator'), ('coordinator', 'Coordinator'), ('mobilograph', 'Mobilographer'), ('it', 'IT Specialist'), ('organizer', 'Organizer'), ('Founder', 'Founder')], default='volunteer', max_length=20, verbose_name='Статус / Роль'),
        ),
    ]
