# Generated by Django 4.2.4 on 2026-07-19 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_telegram', '0041_alter_tguser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectparticipation',
            name='status',
            field=models.CharField(choices=[('approved', '✅ Қабул қилинди (Принят)'), ('attended', '🌟 Келди (Пришел +10 баллов)'), ('rejected', '❌ Рад этилди (Отклонен)')], default='pending', max_length=20, verbose_name='Status'),
        ),
    ]
