# Generated by Django 4.2.4 on 2026-07-20 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_telegram', '0042_alter_projectparticipation_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teammemberyashilqullar',
            options={},
        ),
        migrations.RemoveField(
            model_name='teammemberyashilqullar',
            name='created',
        ),
        migrations.RemoveField(
            model_name='teammemberyashilqullar',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='teammemberyashilqullar',
            name='skills_en',
        ),
        migrations.RemoveField(
            model_name='teammemberyashilqullar',
            name='skills_ru',
        ),
        migrations.RemoveField(
            model_name='teammemberyashilqullar',
            name='skills_uz',
        ),
        migrations.RemoveField(
            model_name='teammemberyashilqullar',
            name='updated',
        ),
        migrations.AddField(
            model_name='teammemberyashilqullar',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='Bio'),
        ),
        migrations.AddField(
            model_name='teammemberyashilqullar',
            name='bio_en',
            field=models.TextField(blank=True, null=True, verbose_name='Bio'),
        ),
        migrations.AddField(
            model_name='teammemberyashilqullar',
            name='bio_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Bio'),
        ),
        migrations.AddField(
            model_name='teammemberyashilqullar',
            name='bio_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Bio'),
        ),
        migrations.AddField(
            model_name='teammemberyashilqullar',
            name='github',
            field=models.URLField(blank=True, null=True, verbose_name='GitHub'),
        ),
        migrations.AddField(
            model_name='teammemberyashilqullar',
            name='linkedin',
            field=models.URLField(blank=True, null=True, verbose_name='LinkedIn'),
        ),
        migrations.AlterField(
            model_name='teammemberyashilqullar',
            name='focus',
            field=models.CharField(choices=[('founder', 'Founder'), ('media', 'Media Lead'), ('organization', 'Organization')], default='organization', max_length=20),
        ),
        migrations.AlterField(
            model_name='teammemberyashilqullar',
            name='fullname',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='teammemberyashilqullar',
            name='instagram',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='teammemberyashilqullar',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='team_photos/'),
        ),
        migrations.AlterField(
            model_name='teammemberyashilqullar',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
