# Generated by Django 4.2.30 on 2026-09-28 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_telegram', '0043_alter_teammemberyashilqullar_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articleimage',
            options={'ordering': ['order'], 'verbose_name': 'Фото', 'verbose_name_plural': 'Фото (галерея)'},
        ),
        migrations.AlterModelOptions(
            name='ecoproject',
            options={'verbose_name': 'Мероприятие', 'verbose_name_plural': 'Мероприятия'},
        ),
        migrations.AlterModelOptions(
            name='ecoprojectimage',
            options={'ordering': ['order'], 'verbose_name': 'Фото мероприятия', 'verbose_name_plural': 'Фото мероприятия (галерея)'},
        ),
        migrations.AlterModelOptions(
            name='eventfeedback',
            options={'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AlterModelOptions(
            name='partner',
            options={'verbose_name': 'Партнёр', 'verbose_name_plural': 'Партнёры'},
        ),
        migrations.AlterModelOptions(
            name='projectparticipation',
            options={'verbose_name': 'Участник', 'verbose_name_plural': 'Участники'},
        ),
        migrations.AlterModelOptions(
            name='tguser',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='ecoproject',
            name='chat_link',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на группу (сюда кидаем сертификаты)'),
        ),
        migrations.AlterField(
            model_name='ecoproject',
            name='date',
            field=models.DateTimeField(verbose_name='Дата и время'),
        ),
        migrations.AlterField(
            model_name='ecoproject',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='ecoproject',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
        migrations.AlterField(
            model_name='ecoproject',
            name='location_name',
            field=models.CharField(max_length=255, verbose_name='Место'),
        ),
        migrations.AlterField(
            model_name='ecoproject',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='projects/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='ecoproject',
            name='region',
            field=models.CharField(choices=[('karakalpakstan', 'Qoraqalpogʻiston Respublikasi'), ('andijon', 'Andijon viloyati'), ('bukhara', 'Buxoro viloyati'), ('fargona', 'Fargʻona viloyati'), ('jizzakh', 'Jizzax viloyati'), ('khorezm', 'Xorazm viloyati'), ('namangan', 'Namangan viloyati'), ('navoi', 'Navoiy viloyati'), ('qashqadaryo', 'Qashqadaryo viloyati'), ('samarkand', 'Samarqand viloyati'), ('sirdaryo', 'Sirdaryo viloyati'), ('surkhandaryo', 'Surxondaryo viloyati'), ('tashkent_v', 'Toshkent viloyati'), ('tashkent_s', 'Toshkent shahri')], default='tashkent_s', max_length=20, verbose_name='Для какого региона'),
        ),
        migrations.AlterField(
            model_name='ecoproject',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='eventfeedback',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='eventfeedback',
            name='rating',
            field=models.PositiveSmallIntegerField(verbose_name='Оценка (1-5)'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='projectparticipation',
            name='applied_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата записи'),
        ),
        migrations.AlterField(
            model_name='projectparticipation',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='app_telegram.ecoproject', verbose_name='Мероприятие'),
        ),
        migrations.AlterField(
            model_name='projectparticipation',
            name='status',
            field=models.CharField(choices=[('approved', '📝 Записан'), ('attended', '✅ Пришёл (+10 баллов)'), ('rejected', '❌ Отклонён')], default='pending', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='projectparticipation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='app_telegram.tguser', verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='balance',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Эко-баллы'),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='education_place',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Место учёбы'),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='experience',
            field=models.TextField(blank=True, null=True, verbose_name='Опыт'),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='fullname',
            field=models.CharField(max_length=255, verbose_name='ФИО'),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='Админ'),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефон'),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='users_photos/', verbose_name='Фото'),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='region',
            field=models.CharField(blank=True, choices=[('karakalpakstan', 'Qoraqalpogʻiston Respublikasi'), ('andijon', 'Andijon viloyati'), ('bukhara', 'Buxoro viloyati'), ('fargona', 'Fargʻona viloyati'), ('jizzakh', 'Jizzax viloyati'), ('khorezm', 'Xorazm viloyati'), ('namangan', 'Namangan viloyati'), ('navoi', 'Navoiy viloyati'), ('qashqadaryo', 'Qashqadaryo viloyati'), ('samarkand', 'Samarqand viloyati'), ('sirdaryo', 'Sirdaryo viloyati'), ('surkhandaryo', 'Surxondaryo viloyati'), ('tashkent_v', 'Toshkent viloyati'), ('tashkent_s', 'Toshkent shahri')], db_index=True, max_length=20, null=True, verbose_name='Регион'),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='role',
            field=models.CharField(choices=[('volunteer', 'Volunteer'), ('head_coordinator', 'Head of Coordinators'), ('main_coordinator', 'Main Coordinator'), ('coordinator', 'Coordinator'), ('mobilograph', 'Mobilographer'), ('it', 'IT Specialist'), ('organizer', 'Organizer'), ('Founder', 'Founder')], db_index=True, default='volunteer', max_length=20, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='tg_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, unique=True, verbose_name='Telegram ID'),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='tguser',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Telegram username'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['article', 'parent'], name='comment_article_parent_idx'),
        ),
        migrations.AddIndex(
            model_name='ecoproject',
            index=models.Index(fields=['is_active', 'date'], name='ecoproj_active_date_idx'),
        ),
        migrations.AddIndex(
            model_name='ecoprojectcomment',
            index=models.Index(fields=['project', 'parent'], name='ecoprojcomment_proj_par_idx'),
        ),
    ]
