import { createContext, useContext, useState, ReactNode } from "react";

export type Lang = "en" | "ru" | "uz";

export const translations = {
  en: {
    // NAV
    navHome: "Home", navAbout: "About", navCommittees: "Committees", navTeam: "Team",
    navSchedule: "Schedule", navRegister: "Register Now", navSponsors: "Sponsors", navContact: "Contact",
    // HOMEPAGE
    dateTag: "MAY 2026 · TASHKENT",
    heroLine1: "Yashil", heroLine2: "Qo'llar", heroLine3: "Model", heroLine4: "United", heroLine5: "Nations",
    heroSub: "Empowering the next generation of global leaders through diplomacy, technology, and sustainable solutions.",
    heroBadge: "3 Days · Registration Open",
    btnRegister: "Register Now", btnCommittees: "View Committees",
    stat0val: "300+", stat0lbl: "Delegates", stat1val: "8", stat1lbl: "Committees",
    stat2val: "40+", stat2lbl: "Countries", stat3val: "3", stat3lbl: "Days",
    councilsLabel: "The Councils", councilsTitle: "Featured Committees", viewAll: "View All Committees",
    ctaTitle1: "Ready to Make", ctaTitle2: "Your Mark?",
    ctaSub: "Registration is open for Yashil Qo'llar MUN 2026. Secure your spot at one of Central Asia's most exciting Model UN conferences.",
    btnContact: "Contact Us",
    homeCommittees: [
      { code: "UNSC", name: "UN Security Council", topic: "Addressing the escalation of tensions in the South China Sea" },
      { code: "UNGA", name: "UN General Assembly", topic: "Reforming the global financial architecture for sustainable development" },
      { code: "WHO", name: "World Health Organization", topic: "Pandemic preparedness and equitable access to vaccines" },
      { code: "ECOSOC", name: "Economic & Social Council", topic: "Digital economy and bridging the technological divide" },
    ],
    // ABOUT
    aboutTag: "About the Conference",
    aboutHero: "Shaping the Future Through",
    aboutHeroEm: "Diplomacy",
    aboutConferenceTag: "The Conference",
    aboutWhatTitle: "What is Model UN?",
    aboutP1: "Model United Nations (MUN) is an educational simulation where students role-play as delegates to the United Nations. Participants research real-world issues, represent countries, debate solutions, and draft resolutions in committee sessions that mirror actual UN meetings.",
    aboutP2: "MUN develops essential 21st-century skills: public speaking, negotiation, research, collaborative problem-solving, cross-cultural communication, and leadership.",
    aboutP3: "Tashkent Tech MUN brings this globally proven educational model to Central Asia, making world-class diplomatic training accessible to students across the region.",
    aboutSteps: [
      { step: "01", title: "Country Assignment", desc: "Each delegate is assigned a country to represent across committee sessions." },
      { step: "02", title: "Research & Preparation", desc: "Delegates research their country's position on the committee's agenda topics." },
      { step: "03", title: "Debate & Negotiation", desc: "In committees, delegates deliver speeches, negotiate, and form blocs." },
      { step: "04", title: "Resolution Drafting", desc: "Delegates collaborate to draft and vote on resolutions to address global issues." },
    ],
    aboutHomeTag: "Our Home",
    aboutHomeTitle: "Tashkent State Technical University",
    aboutHomeP1: "Founded in 1929, Tashkent State Technical University (TSTU) is Uzbekistan's leading engineering and technology institution.",
    aboutHomeP2: "Located in the heart of Tashkent, TSTU provides a world-class venue for international dialogue and academic excellence.",
    aboutValuesTag: "Our Philosophy", aboutValuesTitle: "What We Stand For",
    aboutValues: [
      { icon: "⚖️", title: "Diplomacy", desc: "We believe in the power of dialogue and peaceful negotiation as the cornerstone of international relations." },
      { icon: "🧠", title: "Critical Thinking", desc: "Delegates are encouraged to research deeply, challenge assumptions, and think beyond conventional viewpoints." },
      { icon: "🌐", title: "Global Citizenship", desc: "We foster an understanding of interconnected global challenges and cultivate responsibility toward humanity." },
      { icon: "🚀", title: "Youth Leadership", desc: "Yashil Qo'llar MUN empowers the next generation of leaders with skills that extend far beyond the conference hall." },
    ],
    aboutTimelineTag: "Our Journey", aboutTimelineTitle: "History of Yashil Qo'llar MUN",
    aboutTimeline: [
      { year: "2020", event: "Yashil Qo'llar MUN Founded", desc: "The first edition was held at Tashkent State Technical University with 80 delegates." },
      { year: "2021", event: "Going Regional", desc: "Expanded to include delegates from Uzbekistan, Kazakhstan, and Kyrgyzstan." },
      { year: "2022", event: "International Recognition", desc: "Gained recognition from NMUN and established partnerships with universities abroad." },
      { year: "2023", event: "150+ Delegates", desc: "A milestone edition with participants from 25+ countries." },
      { year: "2024", event: "Flagship Conference", desc: "Yashil Qo'llar MUN became the largest MUN conference in Central Asia." },
      { year: "2026", event: "Yashil Qo'llar MUN 2026", desc: "300+ delegates, 8 committees, 40+ countries — our most ambitious edition yet." },
    ],
    aboutCtaTitle: "Be Part of the Story",
    aboutCtaSub: "Join hundreds of delegates who will gather in Tashkent to shape their futures through diplomacy.",
    aboutCtaBtn: "Register for Yashil Qo'llar MUN 2026",
    // COMMITTEES
    committeesTitle: "Committees",
    committeeLess: "▲ Less", committeeMore: "▼ More",
    committeeSeats: "seats",
    committees: [
      { code: "WHO", name: "World Health Organization", level: "Intermediate", size: "40", topic1: "Global pandemic preparedness and vaccine equity", topic2: "Mental health crisis in conflict-affected regions", chair: "Dr. Alisher Erkinov", desc: "WHO delegates tackle the world's most pressing public health challenges. A strong background in health policy and scientific literacy will be advantageous in this committee.", color: "from-blue-600 to-cyan-500" },
      { code: "ECOSOC", name: "Economic and Social Council", level: "Intermediate", size: "35", topic1: "Digital economy and bridging the technological divide", topic2: "Gender equality and women's economic empowerment in developing nations", chair: "Rustam Khasanov", desc: "ECOSOC coordinates the economic, social, and related work of 14 UN specialized agencies. Delegates will debate policies on sustainable development, poverty reduction, and social equity.", color: "from-green-700 to-emerald-500" },
      { code: "UNHRC", name: "UN Human Rights Council", level: "Intermediate – Advanced", size: "30", topic1: "Human rights implications of artificial intelligence and surveillance technologies", topic2: "Protecting the rights of climate refugees and internally displaced persons", chair: "Sabina Mirzayeva", desc: "The UNHRC is responsible for promoting and protecting human rights globally. Expect passionate debate on sensitive issues requiring careful, evidence-based argumentation.", color: "from-purple-700 to-violet-500" },
      { code: "ICJ", name: "International Court of Justice", level: "Advanced", size: "20", topic1: "State responsibility for cyberattacks on critical infrastructure", topic2: "Jurisdiction over crimes against humanity in failed states", chair: "Otabek Nazarov", desc: "The ICJ simulates proceedings of the principal judicial organ of the United Nations. Delegates serve as judges and legal advocates, presenting oral arguments and applying international law.", color: "from-amber-700 to-yellow-500" },
      { code: "DISEC", name: "Disarmament & International Security Committee", level: "Beginner – Intermediate", size: "45", topic1: "Non-proliferation of nuclear weapons and the NPT regime", topic2: "Autonomous weapons systems and the ethics of lethal AI in warfare", chair: "Feruza Alimova", desc: "DISEC (First Committee of the UNGA) deals with disarmament and matters related to international security. This committee is well-suited for delegates with an interest in geopolitics and defense policy.", color: "from-slate-600 to-gray-500" },
      { code: "SPECPOL", name: "Special Political & Decolonization Committee", level: "Beginner", size: "50", topic1: "Post-colonial reparations and historical accountability", topic2: "The situation in occupied and disputed territories worldwide", chair: "Javokhir Ergashev", desc: "SPECPOL (Fourth Committee) covers a unique combination of political topics — particularly those related to decolonization. Its broad mandate makes it an excellent committee for new delegates.", color: "from-teal-700 to-cyan-600" },
    ],
    // REGISTRATION
    regTag: "Join the Conference", regTitle: "Delegate Registration",
    regSuccessTitle: "Application Received!",
    regSuccessSub: "Thank you for applying. Our team will review your application and contact you via email.",
    regSuccessBtn: "Submit another application",
    regFeesTitle: "Registration Fees",
    fees: [
      { type: "Early Bird", deadline: "April 15, 2026", price: "$25", desc: "Full conference access, delegate kit, all meals, social events", badge: "Best Value", badgeColor: "bg-green-500/10 text-green-400 border-green-500/20" },
      { type: "Regular", deadline: "May 15, 2026", price: "$35", desc: "Full conference access, delegate kit, all meals, social events", badge: "", badgeColor: "" },
      { type: "On-Site", deadline: "May 31, 2026", price: "$45", desc: "Full conference access (no kit guarantee, limited seats)", badge: "Limited", badgeColor: "bg-red-500/10 text-red-400 border-red-500/20" },
    ],
    regDeadline: "Deadline:",
    regFields: { firstName: "First Name", lastName: "Last Name", email: "Email Address", committee1: "1st Committee Preference", committee2: "2nd Committee Preference", experience: "MUN Experience", motivation: "Motivation Statement", motivationPlaceholder: "Why do you want to participate?", selectCommittee: "Select committee", selectExperience: "Select experience level", expNone: "No prior MUN experience", exp12: "1–2 conferences", exp35: "3–5 conferences", exp5: "5+ conferences", submit: "Submit Application" },
    // CONTACT
    contactTitle: "Contact Us",
    contactLocation: "Location",
    contactAddress: "Universitetskaya St. 2/1, Almazar, Tashkent",
    faqTag: "Quick Answers", faqTitle: "Frequently Asked Questions",
    faq: [
      { q: "Who can attend Yashil Qo'llar MUN 2026?", a: "Yashil Qo'llar MUN is open to high school and university students from all countries. No prior MUN experience is required for most committees." },
      { q: "What language are committee sessions held in?", a: "All official committee sessions and communications are conducted in English." },
      { q: "Is accommodation provided?", a: "We can recommend partner hotels near the venue. Details are sent to registered delegates upon confirmation." },
      { q: "When will I receive committee and country assignments?", a: "Assignments are sent by email approximately 3–4 weeks before the conference begins." },
      { q: "Can I attend as a delegation (school group)?", a: "Yes! We welcome school and university delegations. Please contact us for group registration discounts." },
    ],
    // SCHEDULE
    scheduleTag: "Conference Timeline", scheduleTitle: "Official Schedule",
    scheduleCtaTitle: "Ready to Join Us?",
    scheduleCtaSub: "Secure your spot at Yashil Qo'llar MUN 2026 and be part of three unforgettable days of debate, diplomacy, and discovery.",
    scheduleCtaBtn: "Register for Yashil Qo'llar MUN 2026",
    scheduleTypeLabels: { opening: "Ceremony", committee: "Committee", social: "Social", break: "Break", closing: "Closing" },
    scheduleDays: [
      {
        day: "Day 1", date: "May 22, 2026", events: [
          { time: "09:00 – 10:30", title: "Opening Ceremony", subtitle: "Keynote speeches and formal introduction", type: "opening", location: "Main Auditorium" },
          { time: "11:00 – 13:00", title: "Committee Session I", subtitle: "Setting the agenda and opening statements", type: "committee", location: "Committee Rooms" },
          { time: "13:00 – 14:00", title: "Networking Lunch", type: "break", location: "Dining Hall" },
          { time: "19:00 – 21:00", title: "Delegate Social", subtitle: "Evening mixer and cultural performance", type: "social", location: "Grand Ballroom" },
        ]
      },
      {
        day: "Day 3", date: "May 24, 2026", events: [
          { time: "09:00 – 11:00", title: "Committee Session VI", subtitle: "Final debates and passage of resolutions", type: "committee", location: "Committee Rooms" },
          { time: "11:00 – 11:20", title: "Coffee Break", type: "break" },
          { time: "11:20 – 13:00", title: "Crisis Simulation", subtitle: "Special joint committee emergency session", type: "committee", location: "Main Auditorium" },
          { time: "13:00 – 14:00", title: "Lunch Break", type: "break", location: "Dining Hall" },
          { time: "14:00 – 15:30", title: "Press Conference", subtitle: "Committee chairs present adopted resolutions to media", type: "opening", location: "Media Room" },
          { time: "15:30 – 17:00", title: "Closing Ceremony", subtitle: "Best Delegate awards, sponsor recognition, closing remarks", type: "closing", location: "Main Auditorium" },
          { time: "17:00 – 19:00", title: "Farewell Reception", subtitle: "Celebrate with delegates, staff, and guests", type: "social", location: "University Gardens" },
        ]
      },
    ],
    // SPONSORS
    sponsorsStructureTag: "Our Structure", sponsorsStructureTitle: "Conference Councils",
    sponsorsPkgTag: "Partner With Us", sponsorsPkgTitle: "Sponsorship Packages",
    sponsorsPkgSub: "Reach 300+ delegates from 40+ countries and gain brand visibility across Tashkent's most international academic event.",
    sponsorsCtaSub: "Interested in sponsoring Yashil Qo'llar MUN 2026?",
    sponsorsCtaBtn: "Get in Touch",
    // TEAM
    teamSecTag: "The Leadership", teamSecTitle: "Secretariat",
    teamDeptTitle: "Support Departments",
  },

  ru: {
    navHome: "Главная", navAbout: "О нас", navCommittees: "Комитеты", navTeam: "Команда",
    navSchedule: "Расписание", navRegister: "Регистрация", navSponsors: "Спонсоры", navContact: "Контакты",
    dateTag: "МАЙ 2026 · ТАШКЕНТ",
    heroLine1: "Yashil", heroLine2: "Qo'llar", heroLine3: "Модель", heroLine4: "Объединённых", heroLine5: "Наций",
    heroSub: "Воспитываем следующее поколение мировых лидеров через дипломатию, технологии и устойчивые решения.",
    heroBadge: "3 дня · Регистрация открыта",
    btnRegister: "Зарегистрироваться", btnCommittees: "Смотреть комитеты",
    stat0val: "300+", stat0lbl: "Делегатов", stat1val: "8", stat1lbl: "Комитетов",
    stat2val: "40+", stat2lbl: "Стран", stat3val: "3", stat3lbl: "Дня",
    councilsLabel: "Советы", councilsTitle: "Основные комитеты", viewAll: "Все комитеты",
    ctaTitle1: "Готов оставить", ctaTitle2: "след в истории?",
    ctaSub: "Регистрация на Yashil Qo'llar MUN 2026 открыта. Займите своё место на одной из самых ярких MUN-конференций Центральной Азии.",
    btnContact: "Связаться с нами",
    homeCommittees: [
      { code: "СНББООН", name: "Совет Безопасности ООН", topic: "Эскалация напряжённости в Южно-Китайском море" },
      { code: "ГА ООН", name: "Генеральная Ассамблея ООН", topic: "Реформа глобальной финансовой архитектуры для устойчивого развития" },
      { code: "ВОЗ", name: "Всемирная организация здравоохранения", topic: "Готовность к пандемиям и равный доступ к вакцинам" },
      { code: "ЭКОСОС", name: "Экономический и Социальный Совет", topic: "Цифровая экономика и преодоление технологического разрыва" },
    ],
    aboutTag: "О конференции",
    aboutHero: "Формируем будущее через",
    aboutHeroEm: "Дипломатию",
    aboutConferenceTag: "Конференция",
    aboutWhatTitle: "Что такое Модель ООН?",
    aboutP1: "Модель ООН (МУН) — это образовательная симуляция, в которой студенты играют роль делегатов ООН. Участники исследуют реальные проблемы, представляют страны, обсуждают решения и составляют резолюции на комитетских заседаниях.",
    aboutP2: "МУН развивает ключевые навыки XXI века: публичное выступление, переговоры, исследования, совместное решение проблем, межкультурное общение и лидерство.",
    aboutP3: "Tashkent Tech MUN привносит эту глобально проверенную образовательную модель в Центральную Азию, делая дипломатическую подготовку мирового уровня доступной для студентов региона.",
    aboutSteps: [
      { step: "01", title: "Распределение стран", desc: "Каждый делегат получает страну для представления на всех заседаниях комитета." },
      { step: "02", title: "Исследование и подготовка", desc: "Делегаты изучают позицию своей страны по повестке дня комитета." },
      { step: "03", title: "Дебаты и переговоры", desc: "На заседаниях делегаты произносят речи, ведут переговоры и формируют блоки." },
      { step: "04", title: "Составление резолюций", desc: "Делегаты совместно разрабатывают и голосуют за резолюции по глобальным проблемам." },
    ],
    aboutHomeTag: "Наш дом",
    aboutHomeTitle: "Ташкентский государственный технический университет",
    aboutHomeP1: "Основанный в 1929 году, ТГТУ является ведущим инженерно-техническим вузом Узбекистана.",
    aboutHomeP2: "Расположенный в центре Ташкента, ТГТУ предоставляет площадку мирового уровня для международного диалога и академического совершенства.",
    aboutValuesTag: "Наша философия", aboutValuesTitle: "Наши ценности",
    aboutValues: [
      { icon: "⚖️", title: "Дипломатия", desc: "Мы верим в силу диалога и мирных переговоров как основы международных отношений." },
      { icon: "🧠", title: "Критическое мышление", desc: "Делегатов поощряют глубоко исследовать, оспаривать предположения и мыслить нестандартно." },
      { icon: "🌐", title: "Глобальное гражданство", desc: "Мы формируем понимание взаимосвязанных глобальных проблем и воспитываем ответственность перед человечеством." },
      { icon: "🚀", title: "Молодёжное лидерство", desc: "Yashil Qo'llar MUN наделяет следующее поколение лидеров навыками, выходящими далеко за пределы конференц-зала." },
    ],
    aboutTimelineTag: "Наш путь", aboutTimelineTitle: "История Yashil Qo'llar MUN",
    aboutTimeline: [
      { year: "2020", event: "Основание Yashil Qo'llar MUN", desc: "Первое издание прошло в ТГТУ с 80 делегатами." },
      { year: "2021", event: "Региональный охват", desc: "Расширение на делегатов из Узбекистана, Казахстана и Кыргызстана." },
      { year: "2022", event: "Международное признание", desc: "Получили признание от NMUN и установили партнёрство с зарубежными университетами." },
      { year: "2023", event: "150+ делегатов", desc: "Историческое издание с участниками из 25+ стран." },
      { year: "2024", event: "Флагманская конференция", desc: "Yashil Qo'llar MUN стала крупнейшей MUN-конференцией в Центральной Азии." },
      { year: "2026", event: "Yashil Qo'llar MUN 2026", desc: "300+ делегатов, 8 комитетов, 40+ стран — самое амбициозное издание." },
    ],
    aboutCtaTitle: "Стань частью истории",
    aboutCtaSub: "Присоединяйтесь к сотням делегатов, которые соберутся в Ташкенте, чтобы строить своё будущее через дипломатию.",
    aboutCtaBtn: "Зарегистрироваться на Yashil Qo'llar MUN 2026",
    committeesTitle: "Комитеты",
    committeeLess: "▲ Скрыть", committeeMore: "▼ Подробнее",
    committeeSeats: "мест",
    committees: [
      { code: "ВОЗ", name: "Всемирная организация здравоохранения", level: "Средний", size: "40", topic1: "Глобальная готовность к пандемиям и равенство в вакцинации", topic2: "Кризис психического здоровья в зонах конфликтов", chair: "Д-р Алишер Эркинов", desc: "Делегаты ВОЗ рассматривают наиболее острые мировые проблемы здравоохранения.", color: "from-blue-600 to-cyan-500" },
      { code: "ЭКОСОС", name: "Экономический и Социальный Совет", level: "Средний", size: "35", topic1: "Цифровая экономика и преодоление технологического разрыва", topic2: "Гендерное равенство и экономические права женщин в развивающихся странах", chair: "Рустам Хасанов", desc: "ЭКОСОС координирует экономическую и социальную деятельность 14 специализированных агентств ООН.", color: "from-green-700 to-emerald-500" },
      { code: "ССПЧ", name: "Совет ООН по правам человека", level: "Средний – Продвинутый", size: "30", topic1: "Права человека в контексте ИИ и технологий слежки", topic2: "Защита прав климатических беженцев и вынужденных переселенцев", chair: "Сабина Мирзаева", desc: "ССПЧ отвечает за продвижение и защиту прав человека во всём мире.", color: "from-purple-700 to-violet-500" },
      { code: "МСС", name: "Международный суд справедливости", level: "Продвинутый", size: "20", topic1: "Ответственность государств за кибератаки на критическую инфраструктуру", topic2: "Юрисдикция по преступлениям против человечности в несостоявшихся государствах", chair: "Отабек Назаров", desc: "МСС моделирует заседания главного судебного органа ООН.", color: "from-amber-700 to-yellow-500" },
      { code: "ДКВБ", name: "Комитет по разоружению и международной безопасности", level: "Начальный – Средний", size: "45", topic1: "Нераспространение ядерного оружия и режим ДНЯО", topic2: "Автономные системы вооружения и этика летального ИИ", chair: "Феруза Алимова", desc: "ДКВБ занимается вопросами разоружения и международной безопасности.", color: "from-slate-600 to-gray-500" },
      { code: "СПДК", name: "Специальный политический комитет и деколонизация", level: "Начальный", size: "50", topic1: "Репарации за колониализм и историческая ответственность", topic2: "Положение на оккупированных и спорных территориях", chair: "Жавохир Эргашев", desc: "СПДК охватывает широкий круг политических тем, связанных с деколонизацией.", color: "from-teal-700 to-cyan-600" },
    ],
    regTag: "Присоединиться к конференции", regTitle: "Регистрация делегата",
    regSuccessTitle: "Заявка получена!",
    regSuccessSub: "Спасибо за заявку. Наша команда рассмотрит её и свяжется с вами по электронной почте.",
    regSuccessBtn: "Подать ещё одну заявку",
    regFeesTitle: "Регистрационные взносы",
    fees: [
      { type: "Ранняя птица", deadline: "15 апреля 2026", price: "$25", desc: "Полный доступ к конференции, набор делегата, питание, социальные мероприятия", badge: "Лучшая цена", badgeColor: "bg-green-500/10 text-green-400 border-green-500/20" },
      { type: "Стандарт", deadline: "15 мая 2026", price: "$35", desc: "Полный доступ к конференции, набор делегата, питание, социальные мероприятия", badge: "", badgeColor: "" },
      { type: "На месте", deadline: "31 мая 2026", price: "$45", desc: "Полный доступ (набор и места не гарантированы)", badge: "Ограничено", badgeColor: "bg-red-500/10 text-red-400 border-red-500/20" },
    ],
    regDeadline: "Дедлайн:",
    regFields: { firstName: "Имя", lastName: "Фамилия", email: "Электронная почта", committee1: "1-й приоритет комитета", committee2: "2-й приоритет комитета", experience: "Опыт МУН", motivation: "Мотивационное письмо", motivationPlaceholder: "Почему вы хотите участвовать?", selectCommittee: "Выберите комитет", selectExperience: "Выберите уровень опыта", expNone: "Нет опыта МУН", exp12: "1–2 конференции", exp35: "3–5 конференций", exp5: "5+ конференций", submit: "Отправить заявку" },
    contactTitle: "Связаться с нами",
    contactLocation: "Местоположение",
    contactAddress: "ул. Университетская, 2/1, Алмазар, Ташкент",
    faqTag: "Быстрые ответы", faqTitle: "Часто задаваемые вопросы",
    faq: [
      { q: "Кто может участвовать в Yashil Qo'llar MUN 2026?", a: "Конференция открыта для школьников и студентов из всех стран. Опыт МУН не требуется для большинства комитетов." },
      { q: "На каком языке проходят заседания?", a: "Все официальные заседания и коммуникации ведутся на английском языке." },
      { q: "Предоставляется ли жильё?", a: "Мы можем рекомендовать партнёрские отели рядом с площадкой. Детали высылаются зарегистрированным делегатам." },
      { q: "Когда будут распределены комитеты и страны?", a: "Распределение отправляется по электронной почте примерно за 3–4 недели до начала конференции." },
      { q: "Можно ли участвовать делегацией (школьной группой)?", a: "Да! Мы приветствуем школьные и университетские делегации. Свяжитесь с нами для получения групповых скидок." },
    ],
    scheduleTag: "График конференции", scheduleTitle: "Официальное расписание",
    scheduleCtaTitle: "Готовы присоединиться?",
    scheduleCtaSub: "Забронируйте место на Yashil Qo'llar MUN 2026 и станьте частью трёх незабываемых дней дебатов и дипломатии.",
    scheduleCtaBtn: "Зарегистрироваться на Yashil Qo'llar MUN 2026",
    scheduleTypeLabels: { opening: "Церемония", committee: "Комитет", social: "Социальное", break: "Перерыв", closing: "Закрытие" },
    scheduleDays: [
      {
        day: "День 1", date: "22 мая 2026", events: [
          { time: "09:00 – 10:30", title: "Церемония открытия", subtitle: "Keynote-речи и официальное вступление", type: "opening", location: "Главный зал" },
          { time: "11:00 – 13:00", title: "Заседание комитета I", subtitle: "Утверждение повестки и вступительные речи", type: "committee", location: "Комнаты комитетов" },
          { time: "13:00 – 14:00", title: "Нетворкинг-обед", type: "break", location: "Столовая" },
          { time: "19:00 – 21:00", title: "Вечеринка делегатов", subtitle: "Вечерний миксер и культурная программа", type: "social", location: "Большой зал" },
        ]
      },
      {
        day: "День 3", date: "24 мая 2026", events: [
          { time: "09:00 – 11:00", title: "Заседание комитета VI", subtitle: "Финальные дебаты и принятие резолюций", type: "committee", location: "Комнаты комитетов" },
          { time: "11:00 – 11:20", title: "Кофе-пауза", type: "break" },
          { time: "11:20 – 13:00", title: "Кризисная симуляция", subtitle: "Специальное экстренное заседание", type: "committee", location: "Главный зал" },
          { time: "13:00 – 14:00", title: "Обед", type: "break", location: "Столовая" },
          { time: "14:00 – 15:30", title: "Пресс-конференция", subtitle: "Председатели представляют резолюции СМИ", type: "opening", location: "Медиа-зал" },
          { time: "15:30 – 17:00", title: "Церемония закрытия", subtitle: "Награждение лучших делегатов, закрытие", type: "closing", location: "Главный зал" },
          { time: "17:00 – 19:00", title: "Прощальный приём", subtitle: "Торжество с делегатами и гостями", type: "social", location: "Университетский сад" },
        ]
      },
    ],
    sponsorsStructureTag: "Наша структура", sponsorsStructureTitle: "Советы конференции",
    sponsorsPkgTag: "Партнёрство", sponsorsPkgTitle: "Спонсорские пакеты",
    sponsorsPkgSub: "Охватите 300+ делегатов из 40+ стран и получите видимость бренда на самом международном академическом событии Ташкента.",
    sponsorsCtaSub: "Заинтересованы в спонсорстве Yashil Qo'llar MUN 2026?",
    sponsorsCtaBtn: "Связаться с нами",
    teamSecTag: "Руководство", teamSecTitle: "Секретариат",
    teamDeptTitle: "Вспомогательные отделы",
  },

  uz: {
    navHome: "Bosh sahifa", navAbout: "Biz haqimizda", navCommittees: "Qo'mitalar", navTeam: "Jamoa",
    navSchedule: "Jadval", navRegister: "Ro'yxatdan o'tish", navSponsors: "Homiylar", navContact: "Aloqa",
    dateTag: "MAY 2026 · TOSHKENT",
    heroLine1: "Yashil", heroLine2: "Qo'llar", heroLine3: "BMT", heroLine4: "Modeli", heroLine5: "2026",
    heroSub: "Diplomatiya, texnologiya va barqaror yechimlar orqali kelajak dunyo rahbarlarini tarbiyalaymiz.",
    heroBadge: "3 kun · Ro'yxatga olish ochiq",
    btnRegister: "Ro'yxatdan o'tish", btnCommittees: "Qo'mitalarni ko'rish",
    stat0val: "300+", stat0lbl: "Delegat", stat1val: "8", stat1lbl: "Qo'mita",
    stat2val: "40+", stat2lbl: "Mamlakat", stat3val: "3", stat3lbl: "Kun",
    councilsLabel: "Kengashlar", councilsTitle: "Asosiy qo'mitalar", viewAll: "Barcha qo'mitalar",
    ctaTitle1: "O'z izingni", ctaTitle2: "qoldirishga tayyormisan?",
    ctaSub: "Yashil Qo'llar MUN 2026 uchun ro'yxatga olish ochiq. Markaziy Osiyoning eng qiziqarli MUN konferensiyasida o'rningizni band qiling.",
    btnContact: "Biz bilan bog'laning",
    homeCommittees: [
      { code: "XBKK", name: "BMT Xavfsizlik Kengashi", topic: "Janubiy Xitoy dengizidagi keskinlashuv" },
      { code: "BMT GA", name: "BMT Bosh Assambleyasi", topic: "Barqaror rivojlanish uchun moliyaviy me'morchilikni isloh qilish" },
      { code: "JSST", name: "Jahon sog'liqni saqlash tashkiloti", topic: "Pandemiyaga tayyorgarlik va vaksinlarga teng kirish" },
      { code: "EKOSOS", name: "Iqtisodiy va Ijtimoiy Kengash", topic: "Raqamli iqtisodiyot va texnologik tafovutni bartaraf etish" },
    ],
    aboutTag: "Konferensiya haqida",
    aboutHero: "Diplomatiya orqali kelajakni",
    aboutHeroEm: "shakllantiramiz",
    aboutConferenceTag: "Konferensiya",
    aboutWhatTitle: "BMT Modeli nima?",
    aboutP1: "BMT Modeli (MUN) — bu talabalar BMT delegatlari rolini o'ynaydigan ta'lim simulyatsiyasi. Ishtirokchilar real muammolarni o'rganadi, mamlakatlarni ifodalaydi, yechimlarni muhokama qiladi va rezolyutsiyalar tuzadi.",
    aboutP2: "MUN XXI asr uchun zarur ko'nikmalarni rivojlantiradi: jamoatchilik oldida nutq so'zlash, muzokaralar, tadqiqot, hamkorlikda muammolarni hal qilish, madaniyatlararo muloqot va liderlik.",
    aboutP3: "Tashkent Tech MUN bu global ta'lim modelini Markaziy Osiyoga olib keladi.",
    aboutSteps: [
      { step: "01", title: "Mamlakat taqsimoti", desc: "Har bir delegatga barcha qo'mita sessiyalarida vakillik qilish uchun mamlakat beriladi." },
      { step: "02", title: "Tadqiqot va tayyorgarlik", desc: "Delegatlar o'z mamlakatlarining qo'mita kun tartibidagi pozitsiyasini o'rganadilar." },
      { step: "03", title: "Munozara va muzokaralar", desc: "Qo'mitalarda delegatlar nutq so'zlaydi, muzokaralar olib boradi va bloklar tuzadi." },
      { step: "04", title: "Rezolyutsiya tuzish", desc: "Delegatlar global muammolarni hal qilish uchun rezolyutsiyalar ishlab chiqadi va ovoz beradi." },
    ],
    aboutHomeTag: "Bizning uyimiz",
    aboutHomeTitle: "Toshkent davlat texnika universiteti",
    aboutHomeP1: "1929 yilda asos solingan TDTU O'zbekistonning etakchi muhandislik va texnologiya oliy ta'lim muassasasidir.",
    aboutHomeP2: "Toshkent markazida joylashgan TDTU xalqaro muloqot va akademik mukammallik uchun dunyo darajasidagi maydon taqdim etadi.",
    aboutValuesTag: "Bizning falsafamiz", aboutValuesTitle: "Biz nimani himoya qilamiz",
    aboutValues: [
      { icon: "⚖️", title: "Diplomatiya", desc: "Biz muloqot va tinch muzokaralar kuchiga xalqaro munosabatlarning asosi sifatida ishonamiz." },
      { icon: "🧠", title: "Tanqidiy fikrlash", desc: "Delegatlar chuqur tadqiqot qilish, taxminlarni shubha ostiga olish va noan'anaviy fikrlashga undaydi." },
      { icon: "🌐", title: "Global fuqarolik", desc: "Biz o'zaro bog'liq global muammolarni tushunishni va insoniyatga nisbatan mas'uliyatni tarbiyalaymiz." },
      { icon: "🚀", title: "Yoshlar liderligi", desc: "Yashil Qo'llar MUN konferensiya zalidan ancha tashqariga chiqadigan ko'nikmalar bilan kelajak rahbarlarini kuchaytiradi." },
    ],
    aboutTimelineTag: "Bizning yo'limiz", aboutTimelineTitle: "Yashil Qo'llar MUN tarixi",
    aboutTimeline: [
      { year: "2020", event: "Yashil Qo'llar MUN tashkil etildi", desc: "Birinchi nashr TDTU da 80 delegat bilan bo'lib o'tdi." },
      { year: "2021", event: "Mintaqaviy kengayish", desc: "O'zbekiston, Qozog'iston va Qirg'izistondan delegatlar qo'shildi." },
      { year: "2022", event: "Xalqaro tan olinish", desc: "NMUN tomonidan tan olindi va chet el universitetlari bilan hamkorlik o'rnatildi." },
      { year: "2023", event: "150+ delegat", desc: "25+ mamlakatdan ishtirokchilar bilan tarixiy nashr." },
      { year: "2024", event: "Flagman konferensiyasi", desc: "Yashil Qo'llar MUN Markaziy Osiyodagi eng yirik MUN konferensiyasiga aylandi." },
      { year: "2026", event: "Yashil Qo'llar MUN 2026", desc: "300+ delegat, 8 qo'mita, 40+ mamlakat — eng ambitsiyali nashr." },
    ],
    aboutCtaTitle: "Tarixning bir qismi bo'l",
    aboutCtaSub: "Toshkentda to'planadigan va diplomatiya orqali kelajagini shakllantiradigan yuzlab delegatlarga qo'shiling.",
    aboutCtaBtn: "Yashil Qo'llar MUN 2026 ga ro'yxatdan o'tish",
    committeesTitle: "Qo'mitalar",
    committeeLess: "▲ Yig'ish", committeeMore: "▼ Ko'proq",
    committeeSeats: "o'rin",
    committees: [
      { code: "JSST", name: "Jahon sog'liqni saqlash tashkiloti", level: "O'rta", size: "40", topic1: "Global pandemiyaga tayyorgarlik va vaksinalarga teng kirish", topic2: "Nizoli hududlardagi ruhiy salomatlik inqirozi", chair: "Dr. Alisher Erkinov", desc: "JSST delegatlari dunyo sog'liqni saqlashining eng dolzarb muammolarini ko'rib chiqadi.", color: "from-blue-600 to-cyan-500" },
      { code: "EKOSOS", name: "Iqtisodiy va Ijtimoiy Kengash", level: "O'rta", size: "35", topic1: "Raqamli iqtisodiyot va texnologik tafovutni bartaraf etish", topic2: "Rivojlanayotgan mamlakatlarda gender tengligi va ayollarning iqtisodiy huquqlari", chair: "Rustam Xasanov", desc: "EKOSOS 14 ta BMT ixtisoslashgan agentligining iqtisodiy va ijtimoiy ishlarini muvofiqlashtiradi.", color: "from-green-700 to-emerald-500" },
      { code: "INSON", name: "BMT Inson Huquqlari Kengashi", level: "O'rta – Yuqori", size: "30", topic1: "Sun'iy intellekt va kuzatuv texnologiyalarining inson huquqlariga ta'siri", topic2: "Iqlim qochqinlari va ko'chirilgan shaxslar huquqlarini himoya qilish", chair: "Sabina Mirzayeva", desc: "IHK butun dunyoda inson huquqlarini rivojlantirish va himoya qilish uchun mas'ul.", color: "from-purple-700 to-violet-500" },
      { code: "XAD", name: "Xalqaro Adolat Sudi", level: "Yuqori", size: "20", topic1: "Kritik infratuzilmaga kiberxujumlar uchun davlat mas'uliyati", topic2: "Muvaffaqiyatsiz davlatlardagi insoniyatga qarshi jinoyatlar bo'yicha yurisdiktsiya", chair: "Otabek Nazarov", desc: "XAD BMTning asosiy sud organining jarayonlarini simulyatsiya qiladi.", color: "from-amber-700 to-yellow-500" },
      { code: "XQKK", name: "Qurolsizlanish va xalqaro xavfsizlik qo'mitasi", level: "Boshlang'ich – O'rta", size: "45", topic1: "Yadro qurolini tarqatmaslik va YQTSH rejimi", topic2: "Avtonom qurol tizimlari va o'ldiruvchi AIning etikasi", chair: "Feruza Alimova", desc: "XQKK qurolsizlanish va xalqaro xavfsizlik masalalari bilan shug'ullanadi.", color: "from-slate-600 to-gray-500" },
      { code: "SPDK", name: "Maxsus siyosiy va dekolonizatsiya qo'mitasi", level: "Boshlang'ich", size: "50", topic1: "Mustamlakachilikning o'rni va tarixiy javobgarlik", topic2: "Bosib olingan va nizoli hududlardagi vaziyat", chair: "Javokhir Ergashev", desc: "SPDK dekolonizatsiya bilan bog'liq siyosiy mavzularning keng doirasini qamrab oladi.", color: "from-teal-700 to-cyan-600" },
    ],
    regTag: "Konferensiyaga qo'shilish", regTitle: "Delegat ro'yxatga olish",
    regSuccessTitle: "Ariza qabul qilindi!",
    regSuccessSub: "Arizangiz uchun rahmat. Jamoamiz uni ko'rib chiqadi va elektron pochta orqali siz bilan bog'lanadi.",
    regSuccessBtn: "Yana bir ariza yuborish",
    regFeesTitle: "Ro'yxatga olish to'lovlari",
    fees: [
      { type: "Erta qush", deadline: "15 aprel 2026", price: "$25", desc: "Konferensiyaga to'liq kirish, delegat to'plami, barcha ovqatlar, ijtimoiy tadbirlar", badge: "Eng yaxshi narx", badgeColor: "bg-green-500/10 text-green-400 border-green-500/20" },
      { type: "Oddiy", deadline: "15 may 2026", price: "$35", desc: "Konferensiyaga to'liq kirish, delegat to'plami, barcha ovqatlar, ijtimoiy tadbirlar", badge: "", badgeColor: "" },
      { type: "Joyida", deadline: "31 may 2026", price: "$45", desc: "To'liq kirish (to'plam va o'rin kafolatlanmagan)", badge: "Cheklangan", badgeColor: "bg-red-500/10 text-red-400 border-red-500/20" },
    ],
    regDeadline: "Muddat:",
    regFields: { firstName: "Ism", lastName: "Familiya", email: "Elektron pochta", committee1: "1-chi qo'mita afzalligi", committee2: "2-chi qo'mita afzalligi", experience: "MUN tajribasi", motivation: "Motivatsiya xati", motivationPlaceholder: "Nima uchun ishtirok etmoqchisiz?", selectCommittee: "Qo'mitani tanlang", selectExperience: "Tajriba darajasini tanlang", expNone: "MUN tajribasi yo'q", exp12: "1–2 konferensiya", exp35: "3–5 konferensiya", exp5: "5+ konferensiya", submit: "Arizani yuborish" },
    contactTitle: "Biz bilan bog'laning",
    contactLocation: "Joylashuv",
    contactAddress: "Universitetskaya ko'ch. 2/1, Olmazor, Toshkent",
    faqTag: "Tezkor javoblar", faqTitle: "Ko'p so'raladigan savollar",
    faq: [
      { q: "Yashil Qo'llar MUN 2026 da kim ishtirok eta oladi?", a: "Yashil Qo'llar MUN barcha mamlakatlardan maktab va universitet talabalariga ochiq. Ko'pgina qo'mitalar uchun oldingi MUN tajribasi talab qilinmaydi." },
      { q: "Qo'mita sessiyalari qaysi tilda o'tkaziladi?", a: "Barcha rasmiy sessiyalar va muloqotlar ingliz tilida olib boriladi." },
      { q: "Turar joy taqdim etiladi?", a: "Biz maydon yaqinidagi hamkor mehmonxonalarni tavsiya qila olamiz. Tafsilotlar ro'yxatga olingan delegatlarga yuboriladi." },
      { q: "Qo'mita va mamlakat taqsimotini qachon olaman?", a: "Taqsimot konferensiya boshlanishidan taxminan 3–4 hafta oldin elektron pochta orqali yuboriladi." },
      { q: "Delegatsiya (maktab guruhi) sifatida ishtirok eta olamanmi?", a: "Ha! Biz maktab va universitet delegatsiyalarini qabul qilamiz. Guruh chegirmalari uchun biz bilan bog'laning." },
    ],
    scheduleTag: "Konferensiya vaqt jadvali", scheduleTitle: "Rasmiy jadval",
    scheduleCtaTitle: "Bizga qo'shilishga tayyormisiz?",
    scheduleCtaSub: "Yashil Qo'llar MUN 2026 da o'rningizni band qiling va munozara, diplomatiya va kashfiyotning uch unutilmas kuniga qo'shiling.",
    scheduleCtaBtn: "Yashil Qo'llar MUN 2026 ga ro'yxatdan o'tish",
    scheduleTypeLabels: { opening: "Marosim", committee: "Qo'mita", social: "Ijtimoiy", break: "Tanaffus", closing: "Yopilish" },
    scheduleDays: [
      {
        day: "1-kun", date: "22 may 2026", events: [
          { time: "09:00 – 10:30", title: "Ochilish marosimi", subtitle: "Keynote nutqlari va rasmiy tanishuv", type: "opening", location: "Bosh auditoriya" },
          { time: "11:00 – 13:00", title: "Qo'mita sessiyasi I", subtitle: "Kun tartibini belgilash va kirish nutqlari", type: "committee", location: "Qo'mita xonalari" },
          { time: "13:00 – 14:00", title: "Networking tushlik", type: "break", location: "Oshxona" },
          { time: "19:00 – 21:00", title: "Delegatlar kechasi", subtitle: "Kechki tadbirlar va madaniy dastur", type: "social", location: "Grand Ballroom" },
        ]
      },
      {
        day: "3-kun", date: "24 may 2026", events: [
          { time: "09:00 – 11:00", title: "Qo'mita sessiyasi VI", subtitle: "Yakuniy munozaralar va rezolyutsiyalar qabul qilish", type: "committee", location: "Qo'mita xonalari" },
          { time: "11:00 – 11:20", title: "Kofe tanaffusi", type: "break" },
          { time: "11:20 – 13:00", title: "Inqiroz simulyatsiyasi", subtitle: "Maxsus qo'shma qo'mita favqulodda sessiyasi", type: "committee", location: "Bosh auditoriya" },
          { time: "13:00 – 14:00", title: "Tushlik", type: "break", location: "Oshxona" },
          { time: "14:00 – 15:30", title: "Matbuot anjumani", subtitle: "Qo'mita raislari qabul qilingan rezolyutsiyalarni OAVga taqdim etadi", type: "opening", location: "Media xona" },
          { time: "15:30 – 17:00", title: "Yopilish marosimi", subtitle: "Eng yaxshi delegatlarni mukofotlash, yakuniy so'zlar", type: "closing", location: "Bosh auditoriya" },
          { time: "17:00 – 19:00", title: "Xayrlashuv kechasi", subtitle: "Delegatlar va mehmonlar bilan bayram", type: "social", location: "Universitet bog'i" },
        ]
      },
    ],
    sponsorsStructureTag: "Bizning tuzilmamiz", sponsorsStructureTitle: "Konferensiya kengashlari",
    sponsorsPkgTag: "Hamkorlik", sponsorsPkgTitle: "Homiylik paketlari",
    sponsorsPkgSub: "40+ mamlakatdan 300+ delegatga yeting va Toshkentning eng xalqaro akademik tadbirida brend ko'rinishiga ega bo'ling.",
    sponsorsCtaSub: "Yashil Qo'llar MUN 2026 ni homiylik qilishga qiziqasizmi?",
    sponsorsCtaBtn: "Biz bilan bog'laning",
    teamSecTag: "Rahbariyat", teamSecTitle: "Kotibiyat",
    teamDeptTitle: "Yordamchi bo'limlar",
  },
} as const;

export type Translations = typeof translations.en;
interface LangCtx { lang: Lang; setLang: (l: Lang) => void; t: Translations; }
const LanguageContext = createContext<LangCtx>({ lang: "en", setLang: () => { }, t: translations.en });
export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [lang, setLang] = useState<Lang>("en");
  return <LanguageContext.Provider value={{ lang, setLang, t: translations[lang] }}>{children}</LanguageContext.Provider>;
};
export const useLang = () => useContext(LanguageContext);
