# Generated by Django 4.2.4 on 2026-01-20 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_telegram', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammemberyashilqullar',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='team_members/', verbose_name='Rasm'),
        ),
    ]
