# Generated by Django 4.2.4 on 2026-02-17 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_telegram', '0006_tguser_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teammemberyashilqullar',
            old_name='motto',
            new_name='focus',
        ),
    ]
